services:
  app:
    image: blogapp-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: blogapp-frontend
  
  server:
    image: blogapp-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: blogapp-backend
  
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-bloglist
    depends_on:
      - server
      - app